export const fakeKpiDataDash = [
  {
    title: 'Fréquence de visite chez le client',
    labels: [
      'ACME Industries',
      'NovaTech Solutions',
      'Greenline Logistics',
      'Skyport Systems',
      'DeltaConstruct',
      'UrbanEdge Works',
      'HexaFlow Freight',
      'EcoBuild Corp',
      'PrimeMove Group',
      'Zenith Heavy Co.',
      'Triton Equipments',
      'Nexus Materials',
      'BrightCore Infra',
      'Omnia Civil Works',
      'NextGen Transport',
      'LogiPlus Morocco',
      'OmegaTech Rail',
      'BlueCrest Logistics',
      'VeloTrak Services',
      'AstraFleet Ltd.',
      'FastLane Maroc',
      'Innova Hauling',
      'RouteMax Agency',
      'FuturaBlocks',
      'RoboLift SARL',
      'MotionGrid',
      'EcoTrail Movers',
      'Unity Transit',
      'SkyBridge Africa',
    ],
    values: [
      87, 63, 41, 33, 30, 28, 25, 23, 19, 17, 15, 12, 10, 9, 8, 7, 6, 5, 4, 3, 3, 2, 2, 2, 1, 1, 1,
      1, 1,
    ],
  },
  {
    title: 'Durée moyenne de residence en jours',
    labels: [
      'RoboLift SARL',
      'EcoTrail Movers',
      'Zenith Heavy Co.',
      'SkyBridge Africa',
      'BlueCrest Logistics',
      'Skyport Systems',
      'NovaTech Solutions',
      'UrbanEdge Works',
      'ACME Industries',
      'HexaFlow Freight',
      'RouteMax Agency',
      'Omnia Civil Works',
      'PrimeMove Group',
      'FastLane Maroc',
      'Greenline Logistics',
      'EcoBuild Corp',
      'OmegaTech Rail',
      'MotionGrid',
      'AstraFleet Ltd.',
      'Triton Equipments',
      'LogiPlus Morocco',
      'Innova Hauling',
      'Nexus Materials',
      'NextGen Transport',
      'DeltaConstruct',
      'TDM Steel Co.',
      'Unity Transit',
      'FuturaBlocks',
      'VeloTrak Services',
    ],
    values: [
      190.4, 174.2, 160.8, 145.7, 134.3, 121.1, 118.0, 110.5, 102.3, 98.4, 92.6, 85.0, 80.1, 78.3,
      75.2, 70.9, 68.1, 65.0, 60.7, 55.4, 51.2, 47.9, 43.3, 39.6, 36.1, 30.4, 27.7, 18.3, 12.0,
    ],
  },
  {
    title: 'Taux de rotation',
    labels: [
      'UrbanEdge Works',
      'NextGen Transport',
      'HexaFlow Freight',
      'Greenline Logistics',
      'Skyport Systems',
      'EcoTrail Movers',
    ],
    values: [1, 1, 0.94, 0.88, 0.85, 0.79],
  },
]
