import {SplitButton} from 'primereact/splitbutton'
import { DatatableComponent } from '../shared/DatatableComponent/DataTableComponent'

const LocationList = () => {
  let actions = [
    {
      label: 'Supprimer',
      icon: 'pi pi-trash text-red-500',
      command: (e) => {},
    },
    {
      label: 'Modifier',
      icon: 'pi pi-bookmark-fill text-blue-500',
      command: (e) => {},
    },
  ]

  const actionTemplate = (rowData) => {
    actions = actions.map((_i) => ({..._i, data: rowData}))
    return (
      <div>
        <SplitButton
          model={actions}
          className='p-button-help p-button-raised  p-button-outlined p-button-sm'
          icon='pi pi-cog'
        />
      </div>
    )
  }
  const columns = [
    {
      field: '-',
      header: 'Actions',
    },
    {
      field: 'Customername',
      header: 'Client',
    },
    {
      field: 'worksiteName',
      header: 'worksite',
    },
    {
      field: 'reference',
      header: 'Reference',
    },
    {
      field: 'description',
      header: 'Description',
    },
    {
      field: 'rentalDuration',
      header: 'Duration',
    },
    {
      field: 'beginRent',
      header: 'Begin Date',
    },
    {
      field: 'endRent',
      header: 'End Date',
    },
    {
      field: 'creaDate',
      header: 'Date',
    },
    {
      field: 'status',
      header: 'Status',
    },
  ]

  const exportFields = [
    {
      label: 'Client',
      column: 'Customername',
    },
    {
      label: 'worksite',
      column: 'worksiteName',
    },
    {
      label: 'Reference',
      column: 'reference',
    },
    {
      label: 'Description',
      column: 'description',
    },
    {
      label: 'Duration',
      column: 'rentalDuration',
    },
    {
      label: 'Begin Date',
      column: 'beginRent',
    },
    {
      label: 'End Date',
      column: 'endRent',
    },
    {
      label: 'Date',
      column: 'creaDate',
    },
    {
      label: 'Status',
      column: 'status',
    },
  ]

  const fakeData = [
    {
      id: 52,
      reference: 'Rent 08/07/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '08/07/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'VINCI',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 53,
      reference: 'Rent 15/07/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '15/07/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'VAHANA CONSTRUCTION',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 54,
      reference: 'Rent 10/09/2021_34',
      rentalDuration: 500,
      description: '',
      creaDate: '10/09/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SOGEA',
      worksiteName: 'TETOUAN-HIDRO',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 55,
      reference: 'Rent 25/09/2021_17',
      rentalDuration: 500,
      description: '',
      creaDate: '25/09/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SGTM',
      worksiteName: 'BORAN TETOUAN',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 56,
      reference: 'Rent 25/09/2021_27',
      rentalDuration: 500,
      description: '',
      creaDate: '25/09/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SGTM',
      worksiteName: 'USINE YAZAKI-MEKNES',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 57,
      reference: 'Rent 29/09/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '29/09/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'GENERALE ROUTIERE',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 58,
      reference: 'Rent 04/10/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '04/10/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SOUTH WORKS',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 59,
      reference: 'Rent 11/11/2021_22',
      rentalDuration: 500,
      description: '',
      creaDate: '11/11/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SGTM',
      worksiteName: 'PONT SAKIA HAMRA',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 60,
      reference: 'Rent 02/12/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '02/12/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'CBC BTP',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 61,
      reference: 'Rent 15/12/2021_0',
      rentalDuration: 500,
      description: '',
      creaDate: '15/12/2021',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'JESA INSTITUTE',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 62,
      reference: 'Rent 18/01/2022_25',
      rentalDuration: 500,
      description: '',
      creaDate: '18/01/2022',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '11/01/2023',
      Customername: 'SGTM',
      worksiteName: 'UM6P-T2- BENGUERIRE',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 184,
      reference: 'location 06012023',
      rentalDuration: 0,
      description: '1 description',
      creaDate: '17/02/2023',
      beginRent: '-',
      endRent: '-',
      OrderDate: '17/02/2023',
      Customername: 'VINCI',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 190,
      reference: '20230220105442713',
      rentalDuration: 84,
      description: '',
      creaDate: '20/02/2023',
      beginRent: '01/01/1900',
      endRent: '01/01/1900',
      OrderDate: '20/02/2023',
      Customername: 'AHMA',
      worksiteName: 'CHR',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 201,
      reference: 'location 200223',
      rentalDuration: 84,
      description: '1 description',
      creaDate: '20/02/2023',
      beginRent: '-',
      endRent: '-',
      OrderDate: '20/02/2023',
      Customername: 'SEPROB',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 204,
      reference: 'location 2002231',
      rentalDuration: 84,
      description: '1 description',
      creaDate: '20/02/2023',
      beginRent: '-',
      endRent: '-',
      OrderDate: '20/02/2023',
      Customername: 'SEPROB',
      worksiteName: '-',
      status: 'Clôturé',
      codeStatus: 'cloturer',
      color: '#e6e925',
      backgroundColor: '#f7f8dd',
    },
    {
      id: 220,
      reference: '00009-CF',
      rentalDuration: 0,
      description: 'TEST',
      creaDate: '14/03/2023',
      beginRent: '15/03/2023',
      endRent: '28/03/2023',
      OrderDate: '14/03/2023',
      Customername: 'AHMA',
      worksiteName: 'COUR D\u0027APPEL',
      status: 'Crée',
      codeStatus: 'created',
      color: '#008000',
      backgroundColor: '#c6e9c6',
    },
  ]
  return (
    <>
      <h3 className='bg-primary p-2 card text-center'>Locations</h3>
      <DatatableComponent columns={columns} data={fakeData} exportFields={exportFields} />
    </>
  )
}

export default LocationList
