import {SplitButton} from 'primereact/splitbutton'
import {fetchStaffs, selectStaffs} from '../../store/slices/staff.slice'
import {useEffect} from 'react'
import {useAppDispatch, useAppSelector} from '../../hooks'
import {_fetchStaffs} from '../../api'
import {Image} from 'primereact/image'
import { DatatableComponent } from '../shared/DatatableComponent/DataTableComponent'

const StaffList = () => {
  const dispatch = useAppDispatch()
  const list = useAppSelector(selectStaffs)

  let actions = [
    {
      label: 'Supprimer',
      icon: 'pi pi-trash text-red-500',
      command: (e) => {},
    },
    {
      label: 'Modifier',
      icon: 'pi pi-bookmark-fill text-blue-500',
      command: (e) => {},
    },
  ]
  const actionTemplate = (rowData) => {
    actions = actions.map((_i) => ({..._i, data: rowData}))
    return (
      <div>
        <SplitButton
          model={actions}
          className='p-button-help p-button-raised  p-button-outlined p-button-sm'
          icon='pi pi-cog'
        />
      </div>
    )
  }
  const imageTemplate = (rowData) => {
    return <Image src={rowData.image} alt='Image' width='250' preview imageStyle={{objectFit: 'cover', borderRadius: '10px'}} />
  }

  const columns = [
    {field: 'action', header: 'Action', body: actionTemplate},
    {field: 'active', header: 'active', filter: true},
    {field: 'image', header: 'image', body: imageTemplate},
    {field: 'iduser', header: 'iduser', filter: true},
    {field: 'engin', header: 'engin', filter: true},
    {field: 'lastname', header: 'lastname', filter: true},
    {field: 'firstname', header: 'firstname', filter: true},
    {field: 'type', header: 'type', filter: true},
    {field: 'hireday', header: 'hireday', filter: true},
    {field: 'exitday', header: 'exitday', filter: true},
  ]
  const exportFields = [
    {column: 'iduser', label: 'iduser'},
    {column: 'engin', label: 'engin'},
    {column: 'lastname', label: 'lastname'},
    {column: 'firstname', label: 'firstname'},
    {column: 'type', label: 'type'},
    {column: 'hireday', label: 'hireday'},
    {column: 'exitday', label: 'exitday'},
  ]

  const _data = [
    {
      id: 1,
      firstname: 'admin',
      lastname: 'admin',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: null,
      active: 1,
      typeName: null,
      image: 'import/uploads/1profilestaff_3468260.png',
      imageid: 12409,
    },
    {
      id: 3,
      firstname: 'elkhatabi',
      lastname: 'anass',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 4,
      firstname: 'badr',
      lastname: 'badr',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 5,
      firstname: 'Imane',
      lastname: 'EL FATIHI',
      companyId: 1,
      departmentId: null,
      birthday: '10/04/1999',
      hireday: '09/01/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 6,
      firstname: 'OumaimaLN',
      lastname: 'Oumaima',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 19,
      firstname: 'gg',
      lastname: 'gg',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 20,
      firstname: 'staffV',
      lastname: 'staffA',
      companyId: 1,
      departmentId: null,
      birthday: '12/12/2022',
      hireday: '12/11/2022',
      exitday: '12/11/2022',
      typeId: 10,
      active: 1,
      typeName: 'TECHNICIEN',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 21,
      firstname: 'staffVcc',
      lastname: 'staffAccc',
      companyId: 1,
      departmentId: null,
      birthday: '12/12/2022',
      hireday: '12/11/2022',
      exitday: '12/11/2022',
      typeId: 10,
      active: 1,
      typeName: 'TECHNICIEN',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 37,
      firstname: 'EQUIPE',
      lastname: 'TESTEQUIPE',
      companyId: 1,
      departmentId: null,
      birthday: '05/01/2000',
      hireday: '04/12/2022',
      exitday: '07/01/2023',
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 53,
      firstname: 'prenom2',
      lastname: 'nom1',
      companyId: 1,
      departmentId: null,
      birthday: '28/11/2022',
      hireday: '17/12/2022',
      exitday: '19/12/2022',
      typeId: 10,
      active: 1,
      typeName: 'TECHNICIEN',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 56,
      firstname: 'satff_prenom',
      lastname: 'satff_nom',
      companyId: 1,
      departmentId: null,
      birthday: '31/10/2022',
      hireday: '10/01/2023',
      exitday: '03/01/2023',
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 58,
      firstname: 'prenom',
      lastname: 'nomstaff',
      companyId: 1,
      departmentId: null,
      birthday: '28/08/2022',
      hireday: '17/01/2023',
      exitday: '07/02/2023',
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 10065,
      firstname: 'nadia1',
      lastname: 'hachmi1',
      companyId: 1,
      departmentId: null,
      birthday: '28/11/2022',
      hireday: '17/12/2022',
      exitday: '19/12/2022',
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 29,
      firstname: 'fff',
      lastname: 'ffff',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '21/12/2022',
      exitday: null,
      typeId: 10,
      active: 1,
      typeName: 'TECHNICIEN',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 30,
      firstname: 'ggg',
      lastname: 'ggg',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '17/12/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 31,
      firstname: 'gjgg',
      lastname: 'gjgg',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '01/02/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 32,
      firstname: 'testdate2',
      lastname: 'testdate2',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '23/01/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 35,
      firstname: 'testdate3',
      lastname: 'testdate3',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '02/01/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 16,
      firstname: 'nn',
      lastname: 'nn',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: null,
      exitday: null,
      typeId: 10,
      active: 1,
      typeName: 'TECHNICIEN',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 33,
      firstname: 'testdate',
      lastname: 'testdate',
      companyId: 1,
      departmentId: null,
      birthday: null,
      hireday: '02/01/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 10064,
      firstname: 'nadia',
      lastname: 'hachmi',
      companyId: 1,
      departmentId: null,
      birthday: '28/11/2022',
      hireday: '17/12/2022',
      exitday: '19/12/2022',
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
    {
      id: 10066,
      firstname: 'nadia34111',
      lastname: 'hachmi35S12',
      companyId: 1,
      departmentId: null,
      birthday: '28/11/2022',
      hireday: '01/02/2022',
      exitday: null,
      typeId: 9,
      active: 1,
      typeName: 'DIRECTION',
      image: 'import/uploads/nopicture.png',
      imageid: 0,
    },
  ]

  return (
    <>
      <h3 className='bg-primary p-2 card text-center'>Equipes</h3>
      <DatatableComponent columns={columns} data={_data} exportFields={exportFields} />
    </>
  )
}

export default StaffList
